<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body style="padding-left: 5px">
  <h2>HISTORY</h2>
  <p style="padding-left: 10px">PUP traces its roots from the Manila Business School which was founded by the Civil Government of the Philippines and was established on October 19, 1904. It is also referred to as the Manila School of Commerce. The school was delegated to create businessmen and businesswomen for government service and private employment. It was a part of the city school system of Manila which was under the superintendence of Gabriel A. O’Reilly. It held its first classes at a small two-storey building in No. 38 Gunao Street corner Arlegui in Quiapo.</p>

  <p style="padding-left: 10px">The influx of students from different provinces elevated the school's status as an Insular (or national) school and was renamed as Philippine School of Commerce in 1908. The school moved out from its Arlegui building and continued its operation on Goldenberg Mansion located on Gen. Solano Street in San Miguel which was formerly occupied by the Bureau of Audits and the Philippine Senate. Its faculty was composed of Filipino and American teachers. For administrative purposes, the school was placed under the administration of the Superintendent of City Schools but kept its status as a national school.</p>
  
  <p style="padding-left: 10px">In 1933, the school was merged with the Philippine Normal School and the Philippine School of Arts and Trades. During the merger that lasted 12 years, PSC was administered by the PNS Superintendent and its students who completed their courses were considered graduates of Philippine Normal School. The existence of the Philippine School of Commerce caught the attention of President Manuel L. Quezon. In his graduation address on March 26, 1940 at the Rizal Memorial Stadium, he promised a new building for the school where its graduates can be recognized. Two years later, Congressman Manuel A. Alazarte together with the Department Head of the Philippine School of Commerce Luis F. Reyes, formulated a bill to this effect and present it to the Congress. Unfortunately, the plan was not carried out because of the Japanese occupation of the Philippines that occurred between 1942 and 1945 during World War II.</p>

  <p style="padding-left: 10px">Shortly after Philippine liberation, Superintendent Luis F. Reyes resumed the task for the re-establishment and rehabilitation of the school. The Bureau of Public Works released more than ₱8,000 for the repairs and maintenance of public buildings of which the school is a beneficiary. The ruins of the Normal Hall was reconstructed and the college resumed its classes there on August 4, 1946. In 1947, the Philippine Normal School converted the Normal Hall into a dormitory, resulting in the Philippine School of Commerce to resign to its former lot, where it held classes with overcrowded rooms. Because of its unbearable condition, the school made representations in the Philippine Alien Property Administrator, through Malacañang and the Department of Foreign Affairs, for the acquisition of the Lepanto site in Sampaloc. By August 4, 1947 the school transferred to its new Lepanto campus, and Luis F. Reyes was appointed as its superintendent. </p>
  
  <p style="padding-left: 10px">The Philippine School of Commerce was elevated into a college and was renamed as the Philippine College of Commerce in 1952 by virtue of Republic Act 778. Superintendent Luis F. Reyes became the President of the college. It broadened its course offerings and the Annex Building, which had formerly housed the Congress of the Philippines, was turned over to the college. The Business Writers Association of the Philippines awarded the college the title of "Business College of the Year” in 1955. </p>

  <p style="padding-left: 10px">In 1962, Dr. Nemesio E. Prudente was appointed as President. He implemented numerous initiatives that greatly benefits the students such as student loans and the inclusion of the student council in the policy-making body of the college. Three years later, President Diosdado Macapagal proclaimed that the Pandacan site of the Bureau of Animal Industry (which is a slaughterhouse) to be reserved for the exclusive use of the college. In 1968, the college offered social science courses related to business education. Also, the college was granted to use and dispose the A. Mabini Campus in Santa Mesa, Manila adjoining the former site of National Development Corporation, which will eventually become the main and flagship campus of the institution. It was also awarded the title lot for its S.H. Loyola (Lepanto) Campus. As a hotbed of student activism, a handful of its students participated in the First Quarter Storm, one of the factors leading up to the declaration of Martial Law in 1972. </p>

  <p style="padding-left: 10px">The college moved out from its Lepanto campus and completed its transfer to the A. Mabini Campus in 1971. Through Presidential Decree 1341 that was proclaimed on April 1, 1978, the Philippine College of Commerce became a chartered state university and was accordingly renamed as the Polytechnic University of the Philippines. It strengthened PUP Manila campus' hold as the main and flagship campus because it hosts the offices of PUP's Executive Officials. </p>

  <p style="padding-left: 10px">In 1979, the construction of the Main Library, the University Canteen (Sampaguita Building), the Interfaith Chapel, and the addition of 3rd-5th floors of the Main Academic Building was completed (although the 5th floor finished its construction in 1984). The Institute of Technology was also created, which was later known as the College of Engineering and Architecture. Because of the addition of more technical, undergrad and postgraduate programs, PUP adopted the "cluster colleges" setup in 1984, where each college prepared the program and supervise all the subjects required in the degree program offered in the college. </p>

  <p style="padding-left: 10px">In 1986, Dr. Nemesio E. Prudente re-assumed the presidency of PUP. Under his presidency, PUP developed its physical facilities in Manila and in other campuses. He also formulated a new PUP logo, hymn and philosophy and had the University's organization restructured. PUP experience enhancement in its academic and co-curricular programs, upsurge in cultural activities, and maintains a dynamic physical education and sports program during his term. Because of what Prudente did, he was credited with revitalizing public education in the Philippines by institutionalizing much-needed changes in the state university he led, which will eventually become the largest state university. </p>

  <p style="padding-left: 10px">In the 1990s, PUP had its first lady president appointed, Dr. Zenaida A. Olonan. PUP established its Information and Technology Center (ICTC) in 1999. It started its operations a year later in 2000. By February 2000, PUP was conferred by the Commission on Higher Education as a Center of Development for Excellence (CODE) in Information Technology. PUP was also recognized as a Virtual Center for Technology Innovation in Information Technology by the Department of Science and Technology. </p>

  <p style="padding-left: 10px">PUP celebrated its Centennial Year in 2004. The countdown for the Centennial started in 1999. In 2003, President Gloria Macapagal-Arroyo proclaimed 2004 as the "PUP Centennial Year". She also declared that the PUP Mabini Campus be the official and permanent home of the Mabini Shrine. The Shrine was transferred to PUP to protect it from the flood control project of the Metro Manila Development Authority. As a part of its Centennial Year, plans were drawn to construct the Diosdado P. Magapagal Law Center (College of Law Building) in Lepanto Campus and Freedom Plaza. Only the Plaza was constructed and the lot at Lepanto Campus where the Law Center is supposed to stand remains empty. PUP made the world's largest human rainbow during its centennial celebration held in Rizal Park to highlight the signing of the Declaration of Peace to be put before the United Nations. PUP's largest human rainbow is made of 30,365 students, faculty, staff and alumni. </p>

  <p style="padding-left: 10px">In 2005, Dr. Dante G. Guevarra was appointed as the Officer-in-Charge of PUP. A year later, he became the Acting President. Notable achievements during his term include the creation of the web-based application system PUP iApply, the designation of PUP as Southeast Asia's first railway academy in 2007, and PUP becoming as one of the sites for the entire nation's commemoration of the 110th Anniversary of the Proclamation of the Philippine Independence. Among the notable structures built during this time include the Mabini Obelisk, Freedom Plaza, and the Fort Santiago replica walls of the Luntiang Pilipinas Forest Park. Despite these achievements, however, Dr. Guevarra's tenure was also controversial due to allegations of graft and corruption, which was linked to the assassination of the Vice President for Administration during his term, Augustus Cezar. Because of his unsatisfactory performance after the recent events, he was suspended from his duty as the President of PUP along with other University officials that are believed to be involved in the aforementioned the scandals. In March 2012, Emanuel de Guzman was appointed as the new President of PUP after a painstaking transition period. </p>

  <p style="padding-left: 10px">PUP participated in a successful attempt to set a world record for most organ donation pledges in 2014, a project spearheaded by the Department of Health. It broke the record for most organ donation pledges in one hour. 3,548 people signed up in the span of 30 minutes, beating India's 2,755 pledged organ donors. PUP placed 3rd in the "Go Green in the City" contest held at Paris, France in June 2015, representing the Philippines. Engineering students John Paul Santos and Christian Santa Romana won the award for their invention, the ELECTRIFILTER (Electricity Generation from Filthy Water). It generates electricity from waste water, has the capability to filter and cleanse water and is portable so that it can be delivered to places where clean water and electricity are short in supply. </p>

  <p style="padding-left: 10px">In September 2019, multiple bills have been filed in the House of Representatives and the Senate to elevate the status of PUP into the national polytechnic university. Of all the state universities and colleges, only the University of the Philippines have a chartered national university status.</p>
</body>
</html>